from __future__ import annotations

import csv
import io
import json
import os
import re
import shlex
import subprocess
import time
from collections import Counter
from pathlib import Path
from typing import Callable, Dict, List, Optional, Sequence, Tuple


JsonDict = Dict[str, object]
CommandRunner = Callable[..., object]

READONLY_REMEDIATION_COMMANDS = {
    "strm-verify",
    "mv3-cloud-duplicate-video-cleanup",
    "mv3-cloud-browse",
    "mv3-cloud-search",
    "qb-orphan-torrent-cleanup-preview",
    "mp-cleanup-preview",
}


def build_finalize_remediation_plan(
    review_report: JsonDict,
    finalize_run_reports: Sequence[JsonDict],
    *,
    env_file: str = "",
    cloud_media_storage: str = "115-default",
    timeout: int = 20,
) -> JsonDict:
    """Build a readonly follow-up plan for blocked finalize rows.

    The report is intentionally diagnostic: generated commands are dry-run or
    readonly checks. Destructive approval flags are not included.
    """

    finalize_by_identity = _finalize_items_by_identity(finalize_run_reports)
    rows: List[JsonDict] = []
    for review_item in review_report.get("items", []) if isinstance(review_report.get("items"), list) else []:
        if not isinstance(review_item, dict) or review_item.get("decision") != "blocked_after_finalize_gates":
            continue
        key = _identity_key(review_item)
        finalize_item = finalize_by_identity.get(key, {})
        row = _remediation_row(
            review_item,
            finalize_item,
            env_file=env_file,
            cloud_media_storage=cloud_media_storage,
            timeout=timeout,
        )
        rows.append(row)

    category_counts = Counter(str(row.get("category") or "") for row in rows)
    status_counts = Counter(str(row.get("finalize_status") or "") for row in rows)
    return {
        "mode": "readonly-finalize-remediation-plan",
        "source_mode": str(review_report.get("mode") or ""),
        "ok": True,
        "planned_items": len(rows),
        "category_counts": dict(sorted(category_counts.items())),
        "finalize_status_counts": dict(sorted(status_counts.items())),
        "items": rows,
        "settings": {
            "env_file": env_file,
            "cloud_media_storage": cloud_media_storage,
            "timeout": timeout,
        },
        "safety": (
            "readonly remediation plan only; generated commands are diagnostic dry-runs or readonly checks. "
            "No cloud write/delete, STRM write, scrape, Emby delete, qBittorrent action, hlink deletion, "
            "source deletion, or filesystem cleanup is performed by this report."
        ),
    }


def render_finalize_remediation_plan(report: JsonDict, output_format: str) -> str:
    if output_format == "json":
        return json.dumps(report, ensure_ascii=False, indent=2)
    if output_format == "csv":
        return _render_csv(report)
    return _render_markdown(report)


def run_finalize_remediation_plan(
    plan_report: JsonDict,
    *,
    output_dir: str,
    categories: Optional[Sequence[str]] = None,
    stages: Optional[Sequence[str]] = None,
    titles: Optional[Sequence[str]] = None,
    limit: int = 0,
    execute_readonly: bool = False,
    cwd: str = "",
    process_timeout: int = 300,
    command_runner: Optional[CommandRunner] = None,
) -> JsonDict:
    """Run or dry-run readonly commands from a finalize remediation plan.

    This runner is deliberately narrow. It only accepts commands generated by
    build_finalize_remediation_plan, only for a fixed allowlist of readonly
    subcommands, and blocks any approval flag before execution.
    """

    output_base = Path(output_dir)
    output_base.mkdir(parents=True, exist_ok=True)
    category_filter = {str(item) for item in (categories or []) if str(item)}
    stage_filter = {str(item) for item in (stages or []) if str(item)}
    title_filters = [str(item) for item in (titles or []) if str(item)]
    runner = command_runner or subprocess.run
    rows: List[JsonDict] = []
    selected_items = 0

    for item_index, item in enumerate(plan_report.get("items", []) if isinstance(plan_report.get("items"), list) else []):
        if not isinstance(item, dict):
            continue
        category = str(item.get("category") or "")
        title = str(item.get("title") or "")
        if category_filter and category not in category_filter:
            continue
        if title_filters and not any(token in title for token in title_filters):
            continue
        if limit > 0 and selected_items >= limit:
            break
        selected_items += 1
        commands = item.get("commands") if isinstance(item.get("commands"), list) else []
        for command_index, command_item in enumerate(commands):
            if not isinstance(command_item, dict):
                continue
            stage = str(command_item.get("stage") or "")
            if stage_filter and stage not in stage_filter:
                continue
            rows.append(
                _run_remediation_command(
                    item,
                    command_item,
                    item_index=item_index,
                    command_index=command_index,
                    output_base=output_base,
                    execute_readonly=execute_readonly,
                    cwd=cwd,
                    process_timeout=process_timeout,
                    runner=runner,
                )
            )

    status_counts = Counter(str(row.get("status") or "") for row in rows)
    stage_counts = Counter(str(row.get("stage") or "") for row in rows)
    category_counts = Counter(str(row.get("category") or "") for row in rows)
    diagnostic_counts = Counter(str(row.get("diagnostic_ok")) for row in rows if row.get("executed"))
    runner_error_count = sum(1 for row in rows if bool(row.get("runner_error")))
    unsafe_blocked_count = sum(1 for row in rows if row.get("status") == "unsafe_blocked")
    return {
        "mode": "readonly-finalize-remediation-run",
        "source_mode": str(plan_report.get("mode") or ""),
        "ok": runner_error_count == 0 and unsafe_blocked_count == 0,
        "execute_readonly": execute_readonly,
        "selected_items": selected_items,
        "planned_commands": len(rows),
        "executed_commands": sum(1 for row in rows if bool(row.get("executed"))),
        "runner_error_count": runner_error_count,
        "unsafe_blocked_count": unsafe_blocked_count,
        "status_counts": dict(sorted(status_counts.items())),
        "stage_counts": dict(sorted(stage_counts.items())),
        "category_counts": dict(sorted(category_counts.items())),
        "diagnostic_ok_counts": dict(sorted(diagnostic_counts.items())),
        "output_dir": str(output_base),
        "items": rows,
        "settings": {
            "categories": sorted(category_filter),
            "stages": sorted(stage_filter),
            "titles": title_filters,
            "limit": limit,
            "cwd": cwd,
            "process_timeout": process_timeout,
        },
        "safety": (
            "readonly remediation runner only; it executes a fixed allowlist of diagnostic commands, "
            "rewrites report outputs under output_dir, and blocks any approval flag before execution."
        ),
    }


def render_finalize_remediation_run(report: JsonDict, output_format: str) -> str:
    if output_format == "json":
        return json.dumps(report, ensure_ascii=False, indent=2)
    if output_format == "csv":
        return _render_run_csv(report)
    lines = [
        "# Finalize Remediation Run",
        "",
        f"- OK: `{bool(report.get('ok'))}`",
        f"- Execute readonly: `{bool(report.get('execute_readonly'))}`",
        f"- Selected items: `{report.get('selected_items', 0)}`",
        f"- Planned commands: `{report.get('planned_commands', 0)}`",
        f"- Executed commands: `{report.get('executed_commands', 0)}`",
        f"- Runner errors: `{report.get('runner_error_count', 0)}`",
        f"- Status counts: `{report.get('status_counts', {})}`",
        "",
        "| Status | Diagnostic OK | Category | Stage | TMDB | S | Title | Output | Blockers |",
        "| --- | --- | --- | --- | ---: | ---: | --- | --- | --- |",
    ]
    for item in report.get("items", []) if isinstance(report.get("items"), list) else []:
        if not isinstance(item, dict):
            continue
        lines.append(
            "| {status} | {diagnostic} | {category} | {stage} | {tmdbid} | {season} | {title} | {output} | {blockers} |".format(
                status=_escape_cell(str(item.get("status") or "")),
                diagnostic=_escape_cell(str(item.get("diagnostic_ok") if "diagnostic_ok" in item else "")),
                category=_escape_cell(str(item.get("category") or "")),
                stage=_escape_cell(str(item.get("stage") or "")),
                tmdbid=item.get("tmdbid") or "",
                season=item.get("season") or "",
                title=_escape_cell(str(item.get("title") or "")),
                output=_escape_cell(str(item.get("output") or "")),
                blockers=_escape_cell("; ".join(_strings(item.get("diagnostic_blockers")))),
            )
        )
    return "\n".join(lines)


def build_finalize_expected_update_plan(
    plan_report: JsonDict,
    diagnostic_reports: Sequence[JsonDict],
) -> JsonDict:
    """Build a readonly plan for stale expected episode counts."""

    diagnostics_by_key = _diagnostics_by_identity(diagnostic_reports)
    rows: List[JsonDict] = []
    for item in plan_report.get("items", []) if isinstance(plan_report.get("items"), list) else []:
        if not isinstance(item, dict) or item.get("category") != "strm_mismatch":
            continue
        rows.append(_expected_update_row(item, _diagnostics_for_item(diagnostics_by_key, item)))

    status_counts = Counter(str(row.get("status") or "") for row in rows)
    identity_overrides = [row["identity_override"] for row in rows if isinstance(row.get("identity_override"), dict)]
    return {
        "mode": "readonly-finalize-remediation-expected-update-plan",
        "source_mode": str(plan_report.get("mode") or ""),
        "ok": True,
        "planned_items": len(rows),
        "ready_items": sum(1 for row in rows if row.get("status") == "ready_for_expected_update"),
        "manual_review_items": sum(1 for row in rows if row.get("status") != "ready_for_expected_update"),
        "status_counts": dict(sorted(status_counts.items())),
        "items": rows,
        "identity_overrides": identity_overrides,
        "safety": (
            "readonly expected-episode update plan only; it reads existing diagnostic JSON and emits suggested "
            "identity overrides. It does not rewrite batch plans, call MV3/MoviePilot/Emby/qBittorrent, "
            "write STRM/NFO/JPG, delete cloud media, or delete local files."
        ),
    }


def render_finalize_expected_update_plan(report: JsonDict, output_format: str) -> str:
    if output_format == "json":
        return json.dumps(report, ensure_ascii=False, indent=2)
    if output_format == "csv":
        return _render_expected_update_csv(report)
    lines = [
        "# Finalize Expected Episode Update Plan",
        "",
        f"- Ready: `{report.get('ready_items', 0)}` / `{report.get('planned_items', 0)}`",
        f"- Status counts: `{report.get('status_counts', {})}`",
        "- Safety: readonly evidence report only; regenerate upstream plans before cleanup.",
        "",
        "| Status | TMDB | S | Title | Old | New | Blockers |",
        "| --- | ---: | ---: | --- | ---: | ---: | --- |",
    ]
    for item in report.get("items", []) if isinstance(report.get("items"), list) else []:
        if not isinstance(item, dict):
            continue
        lines.append(
            "| {status} | {tmdbid} | {season} | {title} | {old} | {new} | {blockers} |".format(
                status=_escape_cell(str(item.get("status") or "")),
                tmdbid=item.get("tmdbid") or "",
                season=item.get("season") or "",
                title=_escape_cell(str(item.get("title") or "")),
                old=item.get("old_expected_episode_count") or "",
                new=item.get("new_expected_episode_count") or "",
                blockers=_escape_cell("; ".join(_strings(item.get("blockers")))),
            )
        )
    return "\n".join(lines)


def build_finalize_cleanup_remediation_plan(
    finalize_run_report: JsonDict,
    *,
    env_file: str = "",
    cloud_media_storage: str = "115-default",
    timeout: int = 20,
) -> JsonDict:
    """Classify cleanup-preview failures from existing reports only."""

    rows: List[JsonDict] = []
    for item in finalize_run_report.get("items", []) if isinstance(finalize_run_report.get("items"), list) else []:
        if not isinstance(item, dict) or item.get("status") != "failed_cleanup_preview":
            continue
        cleanup_preview = _cleanup_preview_stage_report(item)
        rows.append(
            _cleanup_remediation_row(
                item,
                cleanup_preview,
                env_file=env_file,
                cloud_media_storage=cloud_media_storage,
                timeout=timeout,
            )
        )

    category_counts = Counter(str(row.get("category") or "") for row in rows)
    return {
        "mode": "readonly-finalize-cleanup-remediation-plan",
        "source_mode": str(finalize_run_report.get("mode") or ""),
        "ok": True,
        "planned_items": len(rows),
        "category_counts": dict(sorted(category_counts.items())),
        "items": rows,
        "settings": {
            "env_file": env_file,
            "cloud_media_storage": cloud_media_storage,
            "timeout": timeout,
        },
        "safety": (
            "readonly cleanup remediation plan only; it reads existing finalize and cleanup-preview JSON reports. "
            "It does not call MoviePilot, MV3, Emby, qBittorrent, write STRM/NFO/JPG, delete cloud files, "
            "delete qB tasks, delete hlink roots, or delete source files."
        ),
    }


def render_finalize_cleanup_remediation_plan(report: JsonDict, output_format: str) -> str:
    if output_format == "json":
        return json.dumps(report, ensure_ascii=False, indent=2)
    if output_format == "csv":
        return _render_cleanup_remediation_csv(report)
    lines = [
        "# Finalize Cleanup Remediation Plan",
        "",
        f"- Planned items: `{report.get('planned_items', 0)}`",
        f"- Category counts: `{report.get('category_counts', {})}`",
        "- Safety: readonly classification only; generated commands omit approval flags.",
        "",
        "| Category | TMDB | S | Title | qB Matches | Local Videos | Next action |",
        "| --- | ---: | ---: | --- | ---: | ---: | --- |",
    ]
    for item in report.get("items", []) if isinstance(report.get("items"), list) else []:
        if not isinstance(item, dict):
            continue
        lines.append(
            "| {category} | {tmdbid} | {season} | {title} | {qb} | {videos} | {next_action} |".format(
                category=_escape_cell(str(item.get("category") or "")),
                tmdbid=item.get("tmdbid") or "",
                season=item.get("season") or "",
                title=_escape_cell(str(item.get("title") or "")),
                qb=item.get("qb_match_count", 0),
                videos=item.get("local_video_count", 0),
                next_action=_escape_cell(str(item.get("next_action") or "")),
            )
        )
    return "\n".join(lines)


def _cleanup_preview_stage_report(item: JsonDict) -> JsonDict:
    for stage in item.get("stages", []) if isinstance(item.get("stages"), list) else []:
        if not isinstance(stage, dict) or stage.get("stage") != "cloud_hlink_cleanup_preview":
            continue
        output = str(stage.get("output") or "")
        return _load_command_output(Path(output)) if output else {}
    return {}


def _cleanup_episode_range(item: JsonDict, cleanup_preview: JsonDict, expected_count: int) -> Tuple[int, int]:
    episodes = _ints(item.get("expected_episodes"))
    if episodes:
        return min(episodes), max(episodes)
    expected_min = int(item.get("expected_episode_min") or _nested_int(cleanup_preview, "expected", "episode_min") or 0)
    expected_max = int(item.get("expected_episode_max") or _nested_int(cleanup_preview, "expected", "episode_max") or 0)
    if expected_min or expected_max:
        return expected_min, expected_max
    return (1 if expected_count else 0, expected_count)


def _cleanup_hlink_root(cleanup_preview: JsonDict) -> str:
    direct = _nested_str(cleanup_preview, "hlink", "path")
    if direct:
        return direct
    filesystem = cleanup_preview.get("filesystem") if isinstance(cleanup_preview.get("filesystem"), dict) else {}
    for key in ("hlink_roots", "destination_roots"):
        rows = filesystem.get(key) if isinstance(filesystem.get(key), list) else []
        for row in rows:
            if isinstance(row, dict) and row.get("path"):
                return str(row.get("path") or "")
    return ""


def _cleanup_source_paths(cleanup_preview: JsonDict) -> List[str]:
    filesystem = cleanup_preview.get("filesystem") if isinstance(cleanup_preview.get("filesystem"), dict) else {}
    rows = filesystem.get("source_roots") if isinstance(filesystem.get("source_roots"), list) else []
    paths: List[str] = []
    for row in rows:
        if isinstance(row, dict) and row.get("path"):
            paths.append(str(row.get("path") or ""))
    return _unique_strings(paths)


def _cleanup_remediation_row(
    item: JsonDict,
    cleanup_preview: JsonDict,
    *,
    env_file: str,
    cloud_media_storage: str,
    timeout: int,
) -> JsonDict:
    title = str(item.get("title") or cleanup_preview.get("title") or "")
    tmdbid = int(item.get("tmdbid") or _nested_int(cleanup_preview, "expected", "tmdbid") or 0)
    season = int(item.get("season") or 0)
    expected_count = int(item.get("expected_episode_count") or _nested_int(cleanup_preview, "expected", "episode_count") or 0)
    expected_min, expected_max = _cleanup_episode_range(item, cleanup_preview, expected_count)
    strm_root = str(item.get("strm_root") or "")
    required_prefix = str(item.get("required_target_prefix") or _nested_str(cleanup_preview, "expected", "required_target_prefix") or "")
    cloud_title_path = str(
        item.get("cloud_title_path")
        or item.get("cloud_media_path")
        or _cloud_title_path(str(item.get("cloud_season_path") or ""))
        or _nested_str(cleanup_preview, "expected", "cloud_media_path")
        or ""
    )
    hlink_root = str(_cleanup_hlink_root(cleanup_preview) or item.get("hlink_root") or "")
    source_paths = _unique_strings(_strings(item.get("source_paths")) + _cleanup_source_paths(cleanup_preview))
    blockers = sorted(set(_strings(item.get("blockers")) + _strings(cleanup_preview.get("blockers"))))
    warnings = sorted(set(_strings(item.get("warnings")) + _strings(cleanup_preview.get("warnings"))))
    qb = cleanup_preview.get("qbittorrent") if isinstance(cleanup_preview.get("qbittorrent"), dict) else {}
    fs = cleanup_preview.get("filesystem") if isinstance(cleanup_preview.get("filesystem"), dict) else {}
    hlink = cleanup_preview.get("hlink") if isinstance(cleanup_preview.get("hlink"), dict) else {}
    source_rows = fs.get("source_roots") if isinstance(fs.get("source_roots"), list) else []
    qb_matches = [match for match in qb.get("matches", []) if isinstance(match, dict)] if isinstance(qb.get("matches"), list) else []
    qb_hashes = [str(match.get("hash") or "").lower() for match in qb_matches if _looks_like_full_hash(str(match.get("hash") or ""))]
    local_video_count = _local_video_count(hlink, source_rows)
    category = _cleanup_remediation_category(cleanup_preview, qb_matches, local_video_count)
    if category == "qb_orphan_preview_candidate" and (not source_paths or not hlink_root or not strm_root):
        category = "manual_cleanup_review"
    commands = _cleanup_remediation_commands(
        category=category,
        title=title,
        tmdbid=tmdbid,
        season=season,
        expected_count=expected_count,
        expected_min=expected_min,
        expected_max=expected_max,
        strm_root=strm_root,
        required_prefix=required_prefix,
        cloud_title_path=cloud_title_path,
        hlink_root=hlink_root,
        source_paths=source_paths,
        qb_hashes=qb_hashes,
        qb_matches=qb_matches,
        env_file=env_file,
        cloud_media_storage=cloud_media_storage,
        timeout=timeout,
    )
    return {
        "category": category,
        "next_action": _cleanup_remediation_next_action(category),
        "title": title,
        "tmdbid": tmdbid,
        "season": season,
        "finalize_status": str(item.get("status") or ""),
        "blockers": blockers,
        "warnings": warnings,
        "expected_episode_count": expected_count,
        "expected_episode_min": expected_min,
        "expected_episode_max": expected_max,
        "strm_root": strm_root,
        "required_target_prefix": required_prefix,
        "cloud_title_path": cloud_title_path,
        "hlink_root": hlink_root,
        "source_paths": source_paths,
        "qb_match_count": len(qb_matches),
        "qb_hashes": qb_hashes,
        "qb_match_names": [str(match.get("name") or "") for match in qb_matches],
        "local_video_count": local_video_count,
        "hlink": {
            "exists": bool(hlink.get("exists")),
            "video_count": int(hlink.get("video_count") or 0),
            "non_video_count": int(hlink.get("non_video_count") or 0),
        },
        "source_roots": [
            {
                "path": str(row.get("path") or ""),
                "exists": bool(row.get("exists")),
                "video_count": int(row.get("video_count") or 0),
                "blocked": bool(row.get("blocked")),
                "reason": str(row.get("reason") or ""),
            }
            for row in source_rows
            if isinstance(row, dict)
        ],
        "commands": commands,
    }


def _cleanup_remediation_category(cleanup_preview: JsonDict, qb_matches: Sequence[JsonDict], local_video_count: int) -> str:
    blockers = set(_strings(cleanup_preview.get("blockers")))
    hlink = cleanup_preview.get("hlink") if isinstance(cleanup_preview.get("hlink"), dict) else {}
    if local_video_count > 0:
        return "source_or_wrong_season_review"
    if qb_matches and any(_looks_like_full_hash(str(match.get("hash") or "")) for match in qb_matches):
        return "qb_orphan_preview_candidate"
    if bool(hlink.get("exists")) and int(hlink.get("video_count") or 0) == 0 and int(hlink.get("non_video_count") or 0) > 0:
        return "empty_hlink_root_review"
    if {"hlink_root_missing", "qb_match_required"} & blockers or "qb_torrent_not_found" in blockers:
        return "local_already_absent_no_qb_match"
    if "source_root_check_failed" in blockers:
        return "source_or_wrong_season_review"
    return "manual_cleanup_review"


def _cleanup_remediation_next_action(category: str) -> str:
    return {
        "qb_orphan_preview_candidate": "先运行生成的 qB orphan 只读预览；如果 ready_for_execute=true，再单独审批 qB 任务清理，deleteFiles 必须为 false",
        "empty_hlink_root_review": "只剩非视频 hlink 空根，先运行无审批的 hlink-empty-root-cleanup 复核；删除必须单独加审批",
        "local_already_absent_no_qb_match": "本地 hlink/source 没有视频且 qB 未匹配；缺少 full qB hash，只能作为 no-op/人工复核候选，不能自动删除",
        "source_or_wrong_season_review": "本地源目录仍有视频或匹配到错季/错源；必须人工复核，不能自动删除",
        "manual_cleanup_review": "人工复核 cleanup preview、qB、source/hlink 后再决定下一步",
    }.get(category, "人工复核")


def _cleanup_remediation_commands(
    *,
    category: str,
    title: str,
    tmdbid: int,
    season: int,
    expected_count: int,
    expected_min: int,
    expected_max: int,
    strm_root: str,
    required_prefix: str,
    cloud_title_path: str,
    hlink_root: str,
    source_paths: Sequence[str],
    qb_hashes: Sequence[str],
    qb_matches: Sequence[JsonDict],
    env_file: str,
    cloud_media_storage: str,
    timeout: int,
) -> List[JsonDict]:
    prefix = _safe_prefix(title, tmdbid, season)
    env = f"--env-file {_q(env_file)} " if env_file else ""
    if category == "qb_orphan_preview_candidate":
        hash_args = " ".join(f"--expected-qb-hash {_q(value)}" for value in qb_hashes)
        source_roots = _unique_strings(
            list(source_paths) + [str(match.get("host_content_root") or match.get("host_content_path") or "") for match in qb_matches]
        )
        source_args = " ".join(f"--source-root {_q(value)}" for value in source_roots if value)
        title_contains = _qb_expected_title_contains(title, qb_matches)
        if not qb_hashes or not source_args or not hlink_root or not strm_root:
            return []
        return [
            {
                "stage": "qb_orphan_preview_readonly",
                "command": (
                    f"PYTHONPATH=src python3 -m series_cloud_archiver qb-orphan-torrent-cleanup-preview {env}"
                    f"--title {_q(title)} --expected-tmdbid {tmdbid} {hash_args} {source_args} --hlink-root {_q(hlink_root)} "
                    f"--strm-root {_q(strm_root)} --expected-episode-count {expected_count} "
                    f"--expected-episode-min {expected_min} --expected-episode-max {expected_max} "
                    f"--expected-title-contains {_q(title_contains)} --required-target-prefix {_q(required_prefix)} "
                    f"--cloud-media-path {_q(cloud_title_path)} --cloud-media-storage {_q(cloud_media_storage)} "
                    f"--timeout {timeout} --format json --output {_q(prefix + '-qb-orphan-preview.json')}"
                ),
            }
        ]
    if category == "empty_hlink_root_review" and hlink_root:
        return [
            {
                "stage": "hlink_empty_root_review",
                "command": (
                    "PYTHONPATH=src python3 -m series_cloud_archiver hlink-empty-root-cleanup "
                    f"--title {_q(title)} --expected-tmdbid {tmdbid} --hlink-root {_q(hlink_root)} "
                    f"--format json --output {_q(prefix + '-hlink-empty-root.json')}"
                ),
            }
        ]
    return []


def _diagnostics_by_identity(reports: Sequence[JsonDict]) -> Dict[Tuple[int, int, str], List[JsonDict]]:
    rows: Dict[Tuple[int, int, str], List[JsonDict]] = {}
    for report in reports:
        if not isinstance(report, dict):
            continue
        identity_path = _diagnostic_identity_path(report)
        title = str(report.get("title") or _title_from_path(identity_path) or "")
        tmdbid = int(report.get("tmdbid") or report.get("tmdb_id") or _tmdbid_from_text(identity_path) or 0)
        season = int(report.get("season") or _season_from_text(identity_path) or 0)
        if not title or tmdbid <= 0 or season <= 0:
            continue
        rows.setdefault((tmdbid, season, title), []).append(report)
    return rows


def _diagnostics_for_item(
    diagnostics_by_key: Dict[Tuple[int, int, str], List[JsonDict]],
    item: JsonDict,
) -> Dict[str, JsonDict]:
    title = str(item.get("title") or "")
    tmdbid = int(item.get("tmdbid") or _tmdbid_from_text(str(item.get("strm_root") or item.get("cloud_season_path") or "")) or 0)
    season = int(item.get("season") or 0)
    diagnostics = diagnostics_by_key.get((tmdbid, season, title), [])
    if not diagnostics:
        normalized_title = _normalize_title_key(title)
        for (candidate_tmdbid, candidate_season, candidate_title), candidate_reports in diagnostics_by_key.items():
            if candidate_tmdbid == tmdbid and candidate_season == season and _normalize_title_key(candidate_title) == normalized_title:
                diagnostics = candidate_reports
                break
    if not diagnostics:
        for (candidate_tmdbid, candidate_season, _candidate_title), candidate_reports in diagnostics_by_key.items():
            if candidate_tmdbid == tmdbid and candidate_season == season:
                diagnostics = candidate_reports
                break
    by_mode: Dict[str, JsonDict] = {}
    for report in diagnostics:
        mode = str(report.get("mode") or "")
        if mode == "strm-verify":
            by_mode["strm"] = report
        elif mode == "mv3-cloud-duplicate-video-cleanup-result":
            by_mode["cloud"] = report
    return by_mode


def _expected_update_row(item: JsonDict, diagnostics: Dict[str, JsonDict]) -> JsonDict:
    title = str(item.get("title") or "")
    tmdbid = int(item.get("tmdbid") or _tmdbid_from_text(str(item.get("strm_root") or item.get("cloud_season_path") or "")) or 0)
    season = int(item.get("season") or 0)
    old_count = int(item.get("expected_episode_count") or 0)
    old_min = int(item.get("expected_episode_min") or 0)
    old_max = int(item.get("expected_episode_max") or 0)
    strm_report = diagnostics.get("strm") if isinstance(diagnostics.get("strm"), dict) else {}
    cloud_report = diagnostics.get("cloud") if isinstance(diagnostics.get("cloud"), dict) else {}
    strm_episodes = _diagnostic_strm_episodes(strm_report)
    cloud_episodes = _diagnostic_cloud_episodes(cloud_report)
    blockers: List[str] = []
    warnings: List[str] = []

    if not strm_report:
        blockers.append("strm_diagnostic_missing")
    if not cloud_report:
        blockers.append("cloud_diagnostic_missing")
    if not strm_episodes:
        blockers.append("strm_episode_evidence_missing")
    if not cloud_episodes:
        blockers.append("cloud_episode_evidence_missing")
    if strm_episodes and not _is_contiguous(strm_episodes):
        blockers.append("strm_episodes_not_contiguous")
    if cloud_episodes and not _is_contiguous(cloud_episodes):
        blockers.append("cloud_episodes_not_contiguous")
    if strm_episodes and cloud_episodes and strm_episodes != cloud_episodes:
        blockers.append("strm_cloud_episode_sets_differ")
    blockers.extend(_strm_prefix_blockers(strm_report))
    blockers.extend(_cloud_duplicate_preview_blockers(cloud_report))

    new_episodes = strm_episodes if strm_episodes and strm_episodes == cloud_episodes else []
    new_count = len(new_episodes)
    if new_count and old_count and new_count <= old_count:
        blockers.append("new_episode_count_not_greater_than_old_expected")
    if new_episodes and old_min and min(new_episodes) != old_min:
        warnings.append("episode_min_changed")
    if old_max and new_episodes and max(new_episodes) < old_max:
        blockers.append("new_episode_max_less_than_old_expected_max")

    status = "ready_for_expected_update" if not blockers and new_episodes else "manual_review_required"
    row: JsonDict = {
        "status": status,
        "title": title,
        "tmdbid": tmdbid,
        "season": season,
        "old_expected_episode_count": old_count,
        "old_expected_episode_min": old_min,
        "old_expected_episode_max": old_max,
        "old_expected_episodes": list(range(old_min, old_max + 1)) if old_min and old_max and old_min <= old_max else [],
        "new_expected_episode_count": new_count,
        "new_expected_episode_min": min(new_episodes) if new_episodes else 0,
        "new_expected_episode_max": max(new_episodes) if new_episodes else 0,
        "new_expected_episodes": new_episodes,
        "strm_episode_count": len(strm_episodes),
        "cloud_episode_count": len(cloud_episodes),
        "strm_episodes": strm_episodes,
        "cloud_episodes": cloud_episodes,
        "blockers": sorted(set(blockers)),
        "warnings": sorted(set(warnings)),
        "strm_root": str(item.get("strm_root") or ""),
        "cloud_season_path": str(item.get("cloud_season_path") or ""),
        "evidence": _expected_update_evidence(strm_report, cloud_report),
        "next_action": (
            "把 identity/cloud 预期集数更新为当前 STRM/cloud 连续集数后，重新生成 batch/finalize plan 并重跑 finalize gates"
            if status == "ready_for_expected_update"
            else "人工复核 STRM/cloud 诊断报告，确认是否错季、错剧、缺集或旧预期来源错误"
        ),
    }
    if status == "ready_for_expected_update":
        row["identity_override"] = {
            "match_title": title,
            "title": title,
            "tmdbid": tmdbid,
            "season": season,
            "expected_episodes": new_episodes,
            "method": "finalize_remediation_expected_update",
            "confidence": "needs_regenerated_finalize_validation",
            "note": "STRM and MV3 cloud diagnostics agree on a newer contiguous episode set; rerun gates before cleanup.",
        }
    return row


def _diagnostic_strm_episodes(report: JsonDict) -> List[int]:
    strm = report.get("strm") if isinstance(report.get("strm"), dict) else {}
    combined = strm.get("combined") if isinstance(strm.get("combined"), dict) else {}
    return _ints(combined.get("episodes"))


def _diagnostic_cloud_episodes(report: JsonDict) -> List[int]:
    summary = report.get("summary") if isinstance(report.get("summary"), dict) else {}
    return _ints(summary.get("episodes"))


def _is_contiguous(episodes: Sequence[int]) -> bool:
    values = sorted({int(item) for item in episodes})
    return bool(values) and values == list(range(min(values), max(values) + 1))


def _strm_prefix_blockers(report: JsonDict) -> List[str]:
    blockers: List[str] = []
    strm = report.get("strm") if isinstance(report.get("strm"), dict) else {}
    for root in strm.get("roots", []) if isinstance(strm.get("roots"), list) else []:
        if not isinstance(root, dict):
            continue
        if int(root.get("target_prefix_mismatch_count") or 0) > 0:
            blockers.append("strm_target_prefix_mismatch")
        if int(root.get("forbidden_target_count") or 0) > 0:
            blockers.append("strm_forbidden_target_prefix")
        if _ints(root.get("duplicate_episodes")):
            blockers.append("strm_duplicate_episodes")
        if _ints(root.get("missing_in_range")):
            blockers.append("strm_missing_in_range")
    return blockers


def _cloud_duplicate_preview_blockers(report: JsonDict) -> List[str]:
    summary = report.get("summary") if isinstance(report.get("summary"), dict) else {}
    delete_plan = report.get("delete_plan") if isinstance(report.get("delete_plan"), dict) else {}
    blockers: List[str] = []
    if _ints(summary.get("duplicate_episodes")):
        blockers.append("cloud_duplicate_episodes")
    if _ints(summary.get("missing_in_range")):
        blockers.append("cloud_missing_in_range")
    if int(delete_plan.get("duplicate_video_count") or 0) > 0:
        blockers.append("cloud_duplicate_videos_require_separate_review")
    if int(summary.get("episode_count") or 0) != int(summary.get("protected_strm_target_count") or 0):
        blockers.append("cloud_protected_strm_target_count_mismatch")
    if int(summary.get("episode_count") or 0) != int(summary.get("strm_file_count") or 0):
        blockers.append("cloud_strm_file_count_mismatch")
    return blockers


def _expected_update_evidence(strm_report: JsonDict, cloud_report: JsonDict) -> JsonDict:
    summary = cloud_report.get("summary") if isinstance(cloud_report.get("summary"), dict) else {}
    strm = strm_report.get("strm") if isinstance(strm_report.get("strm"), dict) else {}
    combined = strm.get("combined") if isinstance(strm.get("combined"), dict) else {}
    return {
        "strm_episode_count": combined.get("episode_count"),
        "strm_episode_min": combined.get("episode_min"),
        "strm_episode_max": combined.get("episode_max"),
        "cloud_episode_count": summary.get("episode_count"),
        "cloud_video_file_count": summary.get("video_file_count"),
        "cloud_protected_strm_target_count": summary.get("protected_strm_target_count"),
        "cloud_strm_file_count": summary.get("strm_file_count"),
    }


def _title_from_path(value: str) -> str:
    clean = str(value or "").rstrip("/")
    parts = [part for part in clean.split("/") if part]
    for part in reversed(parts):
        if "tmdbid=" in part:
            return re.sub(r"(?:\s*\(\d{4}\))?\s*\{tmdbid=\d+\}.*$", "", part).strip()
    return ""


def _diagnostic_identity_path(report: JsonDict) -> str:
    for key in ("strm_root", "season_path"):
        value = str(report.get(key) or "")
        if value:
            return value
    strm = report.get("strm") if isinstance(report.get("strm"), dict) else {}
    roots = strm.get("roots") if isinstance(strm.get("roots"), list) else []
    for root in roots:
        if isinstance(root, dict) and root.get("path"):
            return str(root.get("path") or "")
    targets = report.get("protected_strm_targets") if isinstance(report.get("protected_strm_targets"), dict) else {}
    return str(targets.get("root") or "")


def _normalize_title_key(value: str) -> str:
    return re.sub(r"(?:\s*\(\d{4}\))?\s*\{tmdbid=\d+\}.*$", "", str(value or "")).strip().casefold()


def _tmdbid_from_text(text: str) -> int:
    match = re.search(r"\{tmdbid=(\d+)\}", str(text or ""), re.IGNORECASE)
    return int(match.group(1)) if match else 0


def _season_from_text(text: str) -> int:
    matches = re.findall(r"(?i)(?:Season\s*0?(\d+)|S(\d{1,2})(?:E\d{1,3})?)", str(text or ""))
    for left, right in reversed(matches):
        value = left or right
        if value:
            return int(value)
    return 0


def _remediation_row(
    review_item: JsonDict,
    finalize_item: JsonDict,
    *,
    env_file: str,
    cloud_media_storage: str,
    timeout: int,
) -> JsonDict:
    blockers = _strings(finalize_item.get("blockers")) or _split_cell(review_item.get("finalize_blockers")) or _split_cell(review_item.get("reason_summary"))
    category = _category(str(finalize_item.get("status") or review_item.get("finalize_status") or ""), blockers)
    title = str(review_item.get("title") or finalize_item.get("title") or "")
    tmdbid = int(review_item.get("tmdbid") or finalize_item.get("tmdbid") or 0)
    season = int(review_item.get("season") or finalize_item.get("season") or 0)
    expected_count = int(review_item.get("expected_episode_count") or finalize_item.get("expected_episode_count") or 0)
    expected_min, expected_max = _episode_range(review_item, finalize_item, expected_count)
    strm_root = str(finalize_item.get("strm_root") or review_item.get("strm_root") or "")
    cloud_season_path = str(finalize_item.get("cloud_season_path") or finalize_item.get("required_target_prefix") or review_item.get("cloud_media_path") or "")
    cloud_title_path = str(finalize_item.get("cloud_title_path") or _cloud_title_path(cloud_season_path) or "")
    hlink_root = str(finalize_item.get("hlink_root") or _first_cell_value(review_item.get("source_paths")) or "")
    source_paths = _strings(finalize_item.get("source_paths")) or _split_paths_cell(review_item.get("source_paths"))
    source_qb_hashes = _strings(finalize_item.get("source_qb_hashes"))
    required_prefix = str(finalize_item.get("required_target_prefix") or finalize_item.get("strm_target_prefix") or cloud_season_path)
    stage_outputs = _stage_outputs(finalize_item)
    commands = _commands(
        category=category,
        title=title,
        tmdbid=tmdbid,
        season=season,
        expected_count=expected_count,
        expected_min=expected_min,
        expected_max=expected_max,
        strm_root=strm_root,
        cloud_season_path=cloud_season_path,
        cloud_title_path=cloud_title_path,
        hlink_root=hlink_root,
        source_paths=source_paths,
        source_qb_hashes=source_qb_hashes,
        required_prefix=required_prefix,
        env_file=env_file,
        cloud_media_storage=cloud_media_storage,
        timeout=timeout,
    )
    return {
        "category": category,
        "next_action": _next_action(category),
        "title": title,
        "tmdbid": tmdbid,
        "season": season,
        "finalize_status": str(finalize_item.get("status") or review_item.get("finalize_status") or ""),
        "finalize_last_stage": str(review_item.get("finalize_last_stage") or _last_stage(finalize_item) or ""),
        "blockers": sorted(set(blockers)),
        "expected_episode_count": expected_count,
        "expected_episode_min": expected_min,
        "expected_episode_max": expected_max,
        "strm_root": strm_root,
        "cloud_title_path": cloud_title_path,
        "cloud_season_path": cloud_season_path,
        "hlink_root": hlink_root,
        "source_paths": source_paths,
        "source_qb_hashes": source_qb_hashes,
        "stage_outputs": stage_outputs,
        "commands": commands,
    }


def _run_remediation_command(
    plan_item: JsonDict,
    command_item: JsonDict,
    *,
    item_index: int,
    command_index: int,
    output_base: Path,
    execute_readonly: bool,
    cwd: str,
    process_timeout: int,
    runner: CommandRunner,
) -> JsonDict:
    title = str(plan_item.get("title") or "")
    tmdbid = int(plan_item.get("tmdbid") or 0)
    season = int(plan_item.get("season") or 0)
    stage = str(command_item.get("stage") or "")
    raw_command = str(command_item.get("command") or "")
    output_path = output_base / _command_output_name(title, tmdbid, season, stage, command_index)
    row: JsonDict = {
        "status": "planned",
        "executed": False,
        "category": str(plan_item.get("category") or ""),
        "stage": stage,
        "title": title,
        "tmdbid": tmdbid,
        "season": season,
        "item_index": item_index,
        "command_index": command_index,
        "output": str(output_path),
        "original_command": raw_command,
        "command": "",
        "returncode": None,
        "diagnostic_ok": None,
        "diagnostic_blockers": [],
        "diagnostic_warnings": [],
        "runner_error": "",
        "safety_blockers": [],
    }
    safety = _safe_command_tokens(raw_command, output_path)
    if safety.get("skip_reason"):
        row["status"] = "skipped"
        row["skip_reason"] = str(safety.get("skip_reason") or "")
        row["command"] = safety.get("command", "")
        return row
    if safety.get("blockers"):
        row["status"] = "unsafe_blocked"
        row["safety_blockers"] = safety.get("blockers", [])
        row["command"] = safety.get("command", "")
        return row
    argv = [str(item) for item in safety.get("argv", []) if str(item)]
    row["command"] = safety.get("command", "")
    if not execute_readonly:
        return row

    started = time.time()
    try:
        completed = runner(
            argv,
            cwd=cwd or None,
            text=True,
            capture_output=True,
            timeout=process_timeout,
            env={**os.environ, "PYTHONPATH": _py_path(cwd)},
        )
    except subprocess.TimeoutExpired as exc:
        row["status"] = "timeout"
        row["executed"] = True
        row["runner_error"] = f"timeout_after_{process_timeout}s"
        row["stdout"] = _truncate_output(getattr(exc, "stdout", "") or "")
        row["stderr"] = _truncate_output(getattr(exc, "stderr", "") or "")
        row["duration_seconds"] = round(time.time() - started, 3)
        return row
    except Exception as exc:  # pragma: no cover - exercised via injected runner in tests.
        row["status"] = "runner_error"
        row["executed"] = True
        row["runner_error"] = f"{type(exc).__name__}: {exc}"
        row["duration_seconds"] = round(time.time() - started, 3)
        return row

    row["executed"] = True
    row["returncode"] = int(getattr(completed, "returncode", 0))
    row["stdout"] = _truncate_output(str(getattr(completed, "stdout", "") or ""))
    row["stderr"] = _truncate_output(str(getattr(completed, "stderr", "") or ""))
    row["duration_seconds"] = round(time.time() - started, 3)
    diagnostic = _load_command_output(output_path)
    if diagnostic:
        row["diagnostic_ok"] = bool(diagnostic.get("ok"))
        row["diagnostic_blockers"] = _strings(diagnostic.get("blockers"))
        row["diagnostic_warnings"] = _strings(diagnostic.get("warnings"))
        row["diagnostic_mode"] = str(diagnostic.get("mode") or "")
        row["diagnostic_summary"] = _diagnostic_summary(diagnostic)
    else:
        row["diagnostic_ok"] = None
    row["status"] = "executed" if row["returncode"] == 0 else "diagnostic_failed"
    return row


def _safe_command_tokens(command: str, output_path: Path) -> JsonDict:
    blockers: List[str] = []
    try:
        tokens = shlex.split(command)
    except ValueError as exc:
        return {"blockers": [f"command_parse_failed:{exc}"], "argv": [], "command": command}
    if len(tokens) < 4 or tokens[:3] != ["PYTHONPATH=src", "python3", "-m"]:
        return {"skip_reason": "non_executable_note", "argv": tokens, "command": command}
    if tokens[3] != "series_cloud_archiver":
        blockers.append("unsupported_module")
    if len(tokens) < 5:
        blockers.append("subcommand_required")
        subcommand = ""
    else:
        subcommand = tokens[4]
    if subcommand not in READONLY_REMEDIATION_COMMANDS:
        blockers.append(f"unsupported_subcommand:{subcommand}")
    if any(token.startswith("--approve-") for token in tokens):
        blockers.append("approval_flag_forbidden")
    if "--output" in tokens:
        index = tokens.index("--output")
        if index + 1 >= len(tokens):
            blockers.append("output_value_required")
        else:
            tokens[index + 1] = str(output_path)
    else:
        tokens.extend(["--output", str(output_path)])
    if "--format" in tokens:
        index = tokens.index("--format")
        if index + 1 < len(tokens):
            tokens[index + 1] = "json"
        else:
            blockers.append("format_value_required")
    else:
        tokens.extend(["--format", "json"])
    argv = ["python3", "-m", "series_cloud_archiver"] + tokens[4:]
    return {"blockers": sorted(set(blockers)), "argv": argv, "command": shlex.join(argv)}


def _command_output_name(title: str, tmdbid: int, season: int, stage: str, command_index: int) -> str:
    prefix = _safe_prefix(title, tmdbid, season)
    safe_stage = re.sub(r"[^0-9A-Za-z_-]+", "-", stage).strip("-") or f"command-{command_index + 1:02d}"
    return f"{prefix}-{command_index + 1:02d}-{safe_stage}.json"


def _py_path(cwd: str) -> str:
    return str(Path(cwd or ".") / "src") if cwd else "src"


def _load_command_output(path: Path) -> JsonDict:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return payload if isinstance(payload, dict) else {}


def _diagnostic_summary(report: JsonDict) -> JsonDict:
    summary: JsonDict = {}
    if isinstance(report.get("strm"), dict):
        combined = report["strm"].get("combined") if isinstance(report["strm"].get("combined"), dict) else {}
        summary["strm_episode_count"] = combined.get("episode_count")
        summary["strm_episodes"] = combined.get("episodes")
        summary["strm_missing_in_range"] = combined.get("missing_in_range")
    if isinstance(report.get("summary"), dict):
        for key in (
            "video_file_count",
            "episode_count",
            "episodes",
            "missing_in_range",
            "duplicate_episodes",
            "protected_strm_target_count",
            "strm_file_count",
        ):
            if key in report["summary"]:
                summary[key] = report["summary"][key]
    if isinstance(report.get("delete_plan"), dict):
        summary["duplicate_video_count"] = report["delete_plan"].get("duplicate_video_count")
    return summary


def _truncate_output(value: str, limit: int = 4000) -> str:
    if len(value) <= limit:
        return value
    return value[:limit] + "...[TRUNCATED]"


def _commands(
    *,
    category: str,
    title: str,
    tmdbid: int,
    season: int,
    expected_count: int,
    expected_min: int,
    expected_max: int,
    strm_root: str,
    cloud_season_path: str,
    cloud_title_path: str,
    hlink_root: str,
    source_paths: Sequence[str],
    source_qb_hashes: Sequence[str],
    required_prefix: str,
    env_file: str,
    cloud_media_storage: str,
    timeout: int,
) -> List[JsonDict]:
    commands: List[JsonDict] = []
    prefix = _safe_prefix(title, tmdbid, season)
    env = f"--env-file {_q(env_file)} " if env_file else ""
    if category == "strm_mismatch":
        commands.append(
            {
                "stage": "strm_verify_readonly",
                "command": (
                    "PYTHONPATH=src python3 -m series_cloud_archiver strm-verify "
                    f"--title {_q(title)} --strm-root {_q(strm_root)} "
                    f"--expected-episode-count {expected_count} --expected-episode-min {expected_min} --expected-episode-max {expected_max} "
                    f"--required-target-prefix {_q(required_prefix)} --format json --output {_q(prefix + '-strm-verify.json')}"
                ),
            }
        )
        commands.append(
            {
                "stage": "cloud_duplicate_preview_readonly",
                "command": (
                    f"PYTHONPATH=src python3 -m series_cloud_archiver mv3-cloud-duplicate-video-cleanup {env}"
                    f"--season-path {_q(cloud_season_path)} --strm-root {_q(strm_root)} "
                    f"--expected-episode-count {expected_count} --storage {_q(cloud_media_storage)} --timeout {timeout} "
                    f"--format json --output {_q(prefix + '-cloud-duplicate-preview.json')}"
                ),
            }
        )
        return commands
    if category == "cloud_path_missing":
        commands.append(
            {
                "stage": "mv3_cloud_browse_title_readonly",
                "command": (
                    f"PYTHONPATH=src python3 -m series_cloud_archiver mv3-cloud-browse {env}"
                    f"--path {_q(cloud_title_path)} --storage {_q(cloud_media_storage)} --timeout {timeout} "
                    f"--format json --output {_q(prefix + '-cloud-title-browse.json')}"
                ),
            }
        )
        commands.append(
            {
                "stage": "mv3_cloud_search_title_readonly",
                "command": (
                    f"PYTHONPATH=src python3 -m series_cloud_archiver mv3-cloud-search {env}"
                    f"--keyword {_q(title)} --storage {_q(cloud_media_storage)} --timeout {timeout} "
                    f"--format json --output {_q(prefix + '-cloud-search.json')}"
                ),
            }
        )
        return commands
    if category == "cloud_duplicate_delete_review":
        commands.append(
            {
                "stage": "cloud_duplicate_preview_readonly",
                "command": (
                    f"PYTHONPATH=src python3 -m series_cloud_archiver mv3-cloud-duplicate-video-cleanup {env}"
                    f"--season-path {_q(cloud_season_path)} --strm-root {_q(strm_root)} "
                    f"--expected-episode-count {expected_count} --storage {_q(cloud_media_storage)} --timeout {timeout} "
                    f"--format json --output {_q(prefix + '-cloud-duplicate-preview.json')}"
                ),
            }
        )
        commands.append(
            {
                "stage": "approval_required_note",
                "command": "复核 preview 中 duplicate_video_count 和 protected STRM targets 后，另走显式审批删除流程",
            }
        )
        return commands
    if category == "extra_source_media":
        commands.append(
            {
                "stage": "extra_source_media_plan",
                "command": "用对应 batch-pipeline 生成的 15-extra-source-media-plan.json 继续，只做 MV3 scan-source 只读识别；不要删除源目录",
            }
        )
        return commands
    if category == "mp_history_or_qb_mismatch":
        hash_args = " ".join(f"--expected-qb-hash {_q(value)}" for value in source_qb_hashes)
        source_args = " ".join(f"--source-root {_q(value)}" for value in source_paths)
        hlink_args = f"--hlink-root {_q(hlink_root)}" if hlink_root else ""
        if source_qb_hashes and source_paths and hlink_root:
            commands.append(
                {
                    "stage": "qb_orphan_preview_readonly",
                    "command": (
                        f"PYTHONPATH=src python3 -m series_cloud_archiver qb-orphan-torrent-cleanup-preview {env}"
                        f"--title {_q(title)} --expected-tmdbid {tmdbid} {hash_args} {source_args} {hlink_args} "
                        f"--strm-root {_q(strm_root)} --expected-episode-count {expected_count} "
                        f"--expected-episode-min {expected_min} --expected-episode-max {expected_max} "
                        f"--required-target-prefix {_q(required_prefix)} --cloud-media-path {_q(cloud_title_path)} "
                        f"--cloud-media-storage {_q(cloud_media_storage)} --timeout {timeout} "
                        f"--format json --output {_q(prefix + '-qb-orphan-preview.json')}"
                    ),
                }
            )
        commands.append(
            {
                "stage": "mp_cleanup_preview_readonly",
                "command": (
                    f"PYTHONPATH=src python3 -m series_cloud_archiver mp-cleanup-preview {env}"
                    f"--title {_q(title)} --expected-tmdbid {tmdbid} --expected-season {season} "
                    f"--timeout {timeout} --format json --output {_q(prefix + '-mp-cleanup-preview.json')}"
                ),
            }
        )
        return commands
    commands.append(
        {
            "stage": "manual_review",
            "command": "人工查看 finalize stage_outputs、STRM、云盘和本地路径后再决定下一步",
        }
    )
    return commands


def _category(status: str, blockers: Sequence[str]) -> str:
    blocker_set = set(blockers)
    if status == "failed_strm_verify" or any(blocker.startswith("strm_") for blocker in blocker_set):
        return "strm_mismatch"
    if "cloud_duplicate_delete_approval_required" in blocker_set:
        return "cloud_duplicate_delete_review"
    if "cloud_season_path_not_found" in blocker_set:
        return "cloud_path_missing"
    if "source_root_check_failed" in blocker_set or "source_root_contains_video_files" in blocker_set or "hlink_root_contains_video_files" in blocker_set:
        return "extra_source_media"
    if "mp_transfer_history_still_present_use_mp_cleanup" in blocker_set or "qb_torrent_not_found" in blocker_set or "qb_match_required" in blocker_set:
        return "mp_history_or_qb_mismatch"
    return "manual_review"


def _next_action(category: str) -> str:
    return {
        "strm_mismatch": "先重跑 STRM 只读校验并比对云盘季目录，确认缺集/错季后再回到转存或 STRM 修复",
        "cloud_path_missing": "先浏览/搜索 MV3 云盘目录，确认正确 Season 路径或目录命名，再修复 STRM target 或云盘目录",
        "cloud_duplicate_delete_review": "先复核云盘重复视频 dry-run 明细，确认 protected STRM target 完整后再单独审批重复视频删除",
        "extra_source_media": "先处理源目录内 hlink 未覆盖的视频：用 extra-source-media-plan 做 MV3 只读识别或人工排除",
        "mp_history_or_qb_mismatch": "先分别跑 qB orphan/MP cleanup 只读预览，确认 MP 历史、qB hash、source/hlink 根是否精确匹配",
        "manual_review": "人工复核 stage 输出后再决定脚本化动作",
    }.get(category, "人工复核")


def _finalize_items_by_identity(reports: Sequence[JsonDict]) -> Dict[Tuple[int, int, str], JsonDict]:
    rows: Dict[Tuple[int, int, str], JsonDict] = {}
    for report in reports:
        for item in report.get("items", []) if isinstance(report.get("items"), list) else []:
            if isinstance(item, dict):
                rows[_identity_key(item)] = item
    return rows


def _identity_key(item: JsonDict) -> Tuple[int, int, str]:
    return (int(item.get("tmdbid") or 0), int(item.get("season") or 0), str(item.get("title") or ""))


def _episode_range(review_item: JsonDict, finalize_item: JsonDict, expected_count: int) -> Tuple[int, int]:
    episodes = _ints(finalize_item.get("expected_episodes")) or _episodes_from_cell(review_item.get("expected_episodes"))
    if episodes:
        return min(episodes), max(episodes)
    return (1 if expected_count else 0, expected_count)


def _stage_outputs(finalize_item: JsonDict) -> Dict[str, str]:
    outputs: Dict[str, str] = {}
    for stage in finalize_item.get("stages", []) if isinstance(finalize_item.get("stages"), list) else []:
        if isinstance(stage, dict) and stage.get("stage") and stage.get("output"):
            outputs[str(stage["stage"])] = str(stage["output"])
    return outputs


def _last_stage(finalize_item: JsonDict) -> str:
    stages = finalize_item.get("stages") if isinstance(finalize_item.get("stages"), list) else []
    if stages and isinstance(stages[-1], dict):
        return str(stages[-1].get("stage") or "")
    return ""


def _cloud_title_path(path: str) -> str:
    clean = str(path or "").rstrip("/")
    if re.search(r"(?i)/(?:Season\s*0?\d+|第\s*\d+\s*季)$", clean):
        return clean.rsplit("/", 1)[0]
    return clean


def _first_cell_value(value: object) -> str:
    values = _split_paths_cell(value)
    return values[0] if values else ""


def _split_paths_cell(value: object) -> List[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item)]
    if isinstance(value, str):
        return [part.strip() for part in value.split("|") if part.strip()]
    return []


def _split_cell(value: object) -> List[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item)]
    if isinstance(value, str):
        return [part.strip() for part in value.split(";") if part.strip()]
    return []


def _episodes_from_cell(value: object) -> List[int]:
    if isinstance(value, list):
        return _ints(value)
    if not isinstance(value, str):
        return []
    numbers: List[int] = []
    for part in value.split(","):
        token = part.strip()
        if not token:
            continue
        if "-" in token:
            left, right = token.split("-", 1)
            if left.strip().isdigit() and right.strip().isdigit():
                start, end = int(left), int(right)
                if start <= end:
                    numbers.extend(range(start, end + 1))
            continue
        if token.isdigit():
            numbers.append(int(token))
    return sorted(set(numbers))


def _strings(value: object) -> List[str]:
    if isinstance(value, list):
        return [str(item) for item in value if str(item)]
    if isinstance(value, str) and value:
        return [value]
    return []


def _unique_strings(values: Sequence[object]) -> List[str]:
    result: List[str] = []
    seen: set[str] = set()
    for value in values:
        text = str(value or "").strip()
        if text and text not in seen:
            seen.add(text)
            result.append(text)
    return result


def _ints(value: object) -> List[int]:
    if not isinstance(value, list):
        return []
    result: List[int] = []
    for item in value:
        try:
            result.append(int(item))
        except (TypeError, ValueError):
            continue
    return sorted(set(result))


def _safe_prefix(title: str, tmdbid: int, season: int) -> str:
    slug = re.sub(r"[^0-9A-Za-z一-龥]+", "-", f"{title}-{tmdbid}-s{season:02d}").strip("-")
    return slug[-120:] or "finalize-remediation"


def _q(value: object) -> str:
    return shlex.quote(str(value))


def _nested_str(mapping: JsonDict, *keys: str) -> str:
    value: object = mapping
    for key in keys:
        if not isinstance(value, dict):
            return ""
        value = value.get(key)
    return str(value or "")


def _nested_int(mapping: JsonDict, *keys: str) -> int:
    try:
        return int(_nested_str(mapping, *keys) or 0)
    except ValueError:
        return 0


def _looks_like_full_hash(value: str) -> bool:
    return bool(re.match(r"^[a-fA-F0-9]{32,64}$", str(value or "")))


def _local_video_count(hlink: JsonDict, source_rows: Sequence[object]) -> int:
    total = int(hlink.get("video_count") or 0) if isinstance(hlink, dict) else 0
    for row in source_rows:
        if isinstance(row, dict):
            total += int(row.get("video_count") or 0)
    return total


def _qb_expected_title_contains(title: str, matches: Sequence[JsonDict]) -> str:
    folded_title = str(title or "").casefold()
    for match in matches:
        name = str(match.get("name") or "")
        if folded_title and folded_title in name.casefold():
            return title
    for match in matches:
        name = str(match.get("name") or "")
        found = re.split(r"(?i)(?:[._ -]+S\d{1,2}(?:[E._ -]|\b)|[._ -]+\d{4}[._ -])", name, maxsplit=1)[0]
        cleaned = found.strip(" ._-")
        if cleaned:
            return cleaned
    return title


def _render_markdown(report: JsonDict) -> str:
    lines = [
        "# Finalize Remediation Plan",
        "",
        f"- Planned items: `{report.get('planned_items', 0)}`",
        f"- Category counts: `{report.get('category_counts', {})}`",
        "- Safety: readonly plan only; commands are diagnostics/dry-runs and omit write/delete approval flags.",
        "",
        "| Category | Status | TMDB | S | Title | Blockers | Next action |",
        "| --- | --- | ---: | ---: | --- | --- | --- |",
    ]
    for item in report.get("items", []) if isinstance(report.get("items"), list) else []:
        if not isinstance(item, dict):
            continue
        lines.append(
            "| {category} | {status} | {tmdbid} | {season} | {title} | {blockers} | {next_action} |".format(
                category=_escape_cell(str(item.get("category") or "")),
                status=_escape_cell(str(item.get("finalize_status") or "")),
                tmdbid=item.get("tmdbid") or "",
                season=item.get("season") or "",
                title=_escape_cell(str(item.get("title") or "")),
                blockers=_escape_cell("; ".join(_strings(item.get("blockers")))),
                next_action=_escape_cell(str(item.get("next_action") or "")),
            )
        )
    return "\n".join(lines)


def _render_csv(report: JsonDict) -> str:
    fieldnames = [
        "category",
        "next_action",
        "title",
        "tmdbid",
        "season",
        "finalize_status",
        "finalize_last_stage",
        "blockers",
        "expected_episode_count",
        "strm_root",
        "cloud_season_path",
        "hlink_root",
        "source_paths",
        "source_qb_hashes",
        "stage_outputs",
        "commands",
    ]
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for item in report.get("items", []) if isinstance(report.get("items"), list) else []:
        if not isinstance(item, dict):
            continue
        writer.writerow(
            {
                "category": item.get("category", ""),
                "next_action": item.get("next_action", ""),
                "title": item.get("title", ""),
                "tmdbid": item.get("tmdbid", ""),
                "season": item.get("season", ""),
                "finalize_status": item.get("finalize_status", ""),
                "finalize_last_stage": item.get("finalize_last_stage", ""),
                "blockers": "; ".join(_strings(item.get("blockers"))),
                "expected_episode_count": item.get("expected_episode_count", ""),
                "strm_root": item.get("strm_root", ""),
                "cloud_season_path": item.get("cloud_season_path", ""),
                "hlink_root": item.get("hlink_root", ""),
                "source_paths": " | ".join(_strings(item.get("source_paths"))),
                "source_qb_hashes": "; ".join(_strings(item.get("source_qb_hashes"))),
                "stage_outputs": json.dumps(item.get("stage_outputs") or {}, ensure_ascii=False, sort_keys=True),
                "commands": json.dumps(item.get("commands") or [], ensure_ascii=False),
            }
        )
    return output.getvalue().rstrip("\r\n")


def _render_cleanup_remediation_csv(report: JsonDict) -> str:
    fieldnames = [
        "category",
        "next_action",
        "title",
        "tmdbid",
        "season",
        "finalize_status",
        "blockers",
        "warnings",
        "expected_episode_count",
        "strm_root",
        "required_target_prefix",
        "cloud_title_path",
        "hlink_root",
        "source_paths",
        "qb_match_count",
        "qb_hashes",
        "qb_match_names",
        "local_video_count",
        "source_roots",
        "commands",
    ]
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for item in report.get("items", []) if isinstance(report.get("items"), list) else []:
        if not isinstance(item, dict):
            continue
        writer.writerow(
            {
                "category": item.get("category", ""),
                "next_action": item.get("next_action", ""),
                "title": item.get("title", ""),
                "tmdbid": item.get("tmdbid", ""),
                "season": item.get("season", ""),
                "finalize_status": item.get("finalize_status", ""),
                "blockers": "; ".join(_strings(item.get("blockers"))),
                "warnings": "; ".join(_strings(item.get("warnings"))),
                "expected_episode_count": item.get("expected_episode_count", ""),
                "strm_root": item.get("strm_root", ""),
                "required_target_prefix": item.get("required_target_prefix", ""),
                "cloud_title_path": item.get("cloud_title_path", ""),
                "hlink_root": item.get("hlink_root", ""),
                "source_paths": " | ".join(_strings(item.get("source_paths"))),
                "qb_match_count": item.get("qb_match_count", ""),
                "qb_hashes": "; ".join(_strings(item.get("qb_hashes"))),
                "qb_match_names": " | ".join(_strings(item.get("qb_match_names"))),
                "local_video_count": item.get("local_video_count", ""),
                "source_roots": json.dumps(item.get("source_roots") or [], ensure_ascii=False, sort_keys=True),
                "commands": json.dumps(item.get("commands") or [], ensure_ascii=False),
            }
        )
    return output.getvalue().rstrip("\r\n")


def _render_run_csv(report: JsonDict) -> str:
    fieldnames = [
        "status",
        "executed",
        "diagnostic_ok",
        "category",
        "stage",
        "title",
        "tmdbid",
        "season",
        "returncode",
        "output",
        "diagnostic_mode",
        "diagnostic_blockers",
        "diagnostic_warnings",
        "diagnostic_summary",
        "runner_error",
        "safety_blockers",
        "command",
    ]
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for item in report.get("items", []) if isinstance(report.get("items"), list) else []:
        if not isinstance(item, dict):
            continue
        writer.writerow(
            {
                "status": item.get("status", ""),
                "executed": item.get("executed", ""),
                "diagnostic_ok": item.get("diagnostic_ok", ""),
                "category": item.get("category", ""),
                "stage": item.get("stage", ""),
                "title": item.get("title", ""),
                "tmdbid": item.get("tmdbid", ""),
                "season": item.get("season", ""),
                "returncode": item.get("returncode", ""),
                "output": item.get("output", ""),
                "diagnostic_mode": item.get("diagnostic_mode", ""),
                "diagnostic_blockers": "; ".join(_strings(item.get("diagnostic_blockers"))),
                "diagnostic_warnings": "; ".join(_strings(item.get("diagnostic_warnings"))),
                "diagnostic_summary": json.dumps(item.get("diagnostic_summary") or {}, ensure_ascii=False, sort_keys=True),
                "runner_error": item.get("runner_error", ""),
                "safety_blockers": "; ".join(_strings(item.get("safety_blockers"))),
                "command": item.get("command", ""),
            }
        )
    return output.getvalue().rstrip("\r\n")


def _render_expected_update_csv(report: JsonDict) -> str:
    fieldnames = [
        "status",
        "title",
        "tmdbid",
        "season",
        "old_expected_episode_count",
        "old_expected_episode_min",
        "old_expected_episode_max",
        "new_expected_episode_count",
        "new_expected_episode_min",
        "new_expected_episode_max",
        "new_expected_episodes",
        "strm_episode_count",
        "cloud_episode_count",
        "blockers",
        "warnings",
        "strm_root",
        "cloud_season_path",
        "next_action",
    ]
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=fieldnames, extrasaction="ignore")
    writer.writeheader()
    for item in report.get("items", []) if isinstance(report.get("items"), list) else []:
        if not isinstance(item, dict):
            continue
        writer.writerow(
            {
                "status": item.get("status", ""),
                "title": item.get("title", ""),
                "tmdbid": item.get("tmdbid", ""),
                "season": item.get("season", ""),
                "old_expected_episode_count": item.get("old_expected_episode_count", ""),
                "old_expected_episode_min": item.get("old_expected_episode_min", ""),
                "old_expected_episode_max": item.get("old_expected_episode_max", ""),
                "new_expected_episode_count": item.get("new_expected_episode_count", ""),
                "new_expected_episode_min": item.get("new_expected_episode_min", ""),
                "new_expected_episode_max": item.get("new_expected_episode_max", ""),
                "new_expected_episodes": ",".join(str(value) for value in _ints(item.get("new_expected_episodes"))),
                "strm_episode_count": item.get("strm_episode_count", ""),
                "cloud_episode_count": item.get("cloud_episode_count", ""),
                "blockers": "; ".join(_strings(item.get("blockers"))),
                "warnings": "; ".join(_strings(item.get("warnings"))),
                "strm_root": item.get("strm_root", ""),
                "cloud_season_path": item.get("cloud_season_path", ""),
                "next_action": item.get("next_action", ""),
            }
        )
    return output.getvalue().rstrip("\r\n")


def _escape_cell(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")
